server:
  port: 8080
#  tomcat:
#    threads:
#      max: 10

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: base-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos中心地址
        namespace: public
        group: DEFAULT_GROUP
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8092 #sentinel控制台地址
        port: 8719 #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      eager: true
      datasource:
        ds1:
          nacos: #sentinel持久化，在nacos配置中心配置流控规则
            server-addr: 127.0.0.1:8848
            dataId: base-web-sentinel.json
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
  main:
    allow-bean-definition-overriding: true #允许存在多个Feign调用相同Service的接口，后来发现的bean会覆盖之前相同名称的bean
  redis:
    #Redis服务器地址
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    password: foobared
             #连接超时时间（毫秒）
    timeout: 10000

#指定日志配置文件，默认是log4j2-spring.xml，推荐使用log4j2.xml
logging:
   config: classpath:log4j2.xml
   level:
      com.alibaba.nacos.client.naming: warn

feign:
#  client:
#    config:
#      default: 
#        connectTimeout: 1000 # 设置超时
#        readTimeout: 1000
#        retryer: NEVER_RETRY
#  httpclient: 
#    connection-timeout: 5000
  #开启Hystrix降级处理
#  hystrix: 
#    enabled: false
  #feign整合sentinel
  sentinel:
    enabled: true
    
#ribbon:
#  #ribbon饥饿模式
#  eager-load:
#    enabled: true
#    clients: base-service
#  #超时
#  ReadTimeout: 5000
#  ConnectTimeout: 5000
    
#服务监控
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
      
#rockermq配置
rocketmq:
  name-server: 172.16.180.93:9876 #rocketmq的NameServer地址
  producer:
    group: my_test_producer_group # 生产者端配置

      
      
